/***************************************************************************
*                               Sunplus mMedia Inc.
*                                 
*       (c) Copyright 2007, SUNPLUS mMedia Inc., Hsinchu, Taiwan R.O.C.
*                               All Right Reserved
****************************** Shi-Jay Weng *******************************/
#ifndef _EX_FLASH_CODE_H_
#define _EX_FLASH_CODE_H_

extern unsigned char code QUICKPAGE[];
extern unsigned int code MAPRAM_PTR[];                            

#endif