/***************************************************************************
*                               Sunplus mMedia Inc.
*                                 
*       (c) Copyright 2007, SUNPLUS mMedia Inc., Hsinchu, Taiwan R.O.C.
*                               All Right Reserved
****************************** Shi-Jay Weng *******************************/
#ifndef SPDA2K_H
#define SPDA2K_H

#include    <stdio.h>
#include    <stdlib.h>
#include    <string.h> 
//#include    <time.h>
#include    "define.h"                  /* definition                    */
#include    "const.h"                   /* Constant definition            */
#include    "UI_CONFIG.h"                   /* UI definition            */
//#include    "ctrlreg.h"                 /* Fairy FPGA specific address    */
#include    "system.h"                  /* 8032 system definitions        */
#include    "prototyp.h"                /* Function Prototype Definition  */
#include    "exglobal.h"                /* The same as  gobal.h           */
#include    "Rambase.h"                 /* RAM base           		  */
#include    "DSP.h"
#include    "EXCODE.h"                 	/* CODE Data          		  */
#include    "EX_USB_Data.h"             /* USB Data          		  */
#include    "EX_Flash_code.h"
#include    "feature_flag.h"
#include    "utility/utility.h"

#endif