SET C51INC=C:\Keil\C51\INC\Dallas\;C:\Keil\C51\INC\
SET C51LIB=C:\Keil\C51\LIB
SET CPU_TYPE=DS80C323
SET CPU_VENDOR=Dallas Semiconductor
SET UV2_TARGET=SPDA2635-NAND-Car-STN
SET CPU_XTAL=0x0112A880
"C:\Keil\C51\BIN\A51.EXE" @.\obj\STARTUP._ia
"C:\Keil\C51\BIN\A51.EXE" @.\obj\L51_BANK._ia
"C:\Keil\C51\BIN\C51.EXE" @.\obj\L51_BA~1.__I
"C:\Keil\C51\BIN\A51.EXE" @.\obj\L51_BA~1._IA
"C:\Keil\C51\BIN\A51.EXE" @.\obj\lib._ia
"C:\Keil\C51\BIN\C51.EXE" @.\obj\USB.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\USB_BULK.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\usb_cmds.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\USB_EP0.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\usbComm.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\system.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\ISR.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\St_cmds.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\CONST_~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\init.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\VARIAB~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\Memalloc.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\PLAY_P~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\Lyric.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\id3.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\MCU_DS~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\FFR1.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\PROCES~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\USB_PR~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\logData.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\remote.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\FM.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\LCM_BMP.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\LCM_BM~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\LCM_UN~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\DIR_PR~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\PlayMenu.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\Menu_Hzk.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\ui.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\ui_impl.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\i2c_sim.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\i2c.__i
"C:\Keil\C51\BIN\C51.EXE" @.\obj\TCA841~1.__I
"C:\Keil\C51\BIN\C51.EXE" @.\obj\utility.__i
"C:\Keil\C51\BIN\BL51.EXE" @.\obj\SPDA23xx.lnp
"C:\Keil\C51\BIN\OC51.EXE" ".\obj\SPDA23xx" 
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B00" HEXFILE(.\obj\SPDA23xx.H00)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B01" HEXFILE(.\obj\SPDA23xx.H01)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B02" HEXFILE(.\obj\SPDA23xx.H02)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B03" HEXFILE(.\obj\SPDA23xx.H03)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B04" HEXFILE(.\obj\SPDA23xx.H04)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B05" HEXFILE(.\obj\SPDA23xx.H05)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B06" HEXFILE(.\obj\SPDA23xx.H06)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B07" HEXFILE(.\obj\SPDA23xx.H07)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B08" HEXFILE(.\obj\SPDA23xx.H08)
"C:\Keil\C51\BIN\OH51.EXE" ".\obj\SPDA23xx.B09" HEXFILE(.\obj\SPDA23xx.H09)
Make_2635_Car_NAND.bat
