/***************************************************************************
*                               Sunplus mMedia Inc.
*                                 
*       (c) Copyright 2007, SUNPLUS mMedia Inc., Hsinchu, Taiwan R.O.C.
*                               All Right Reserved
****************************** Shi-Jay Weng *******************************/
extern unsigned char code QUICKPAGE[];
extern unsigned int code MAPRAM_PTR[];                            